version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.35
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./dockerfiles/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    container_name: my-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
volumes:
  db-store: